sudo: false
language: python

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.cache/pip

env:
  global:
    - "PYPI_USERNAME=angrychimp"

    # This contains the following variables:
    #  - PYPI_PASSWORD
    #
    - secure: ""

install:
  - "pip install --upgrade pip setuptools"
  - "pip install --upgrade tox"
  - "pip install -r dev_requirements.txt"
  - "git fetch origin"

jobs:
  include:
    - env: "TOXENV=lint"
    - env: "TOXENV=check_release_file"
    - env: "TOXENV=py27"
      python: "2.7"
    - env: "TOXENV=py35"
      python: "3.5"
    - env: "TOXENV=py36"
      python: "3.6"
    - env: "TOXENV=deploy"
      stage: "deploy"

stages:
  - "test"
  - name: "deploy"
    if: "type = push"

script:
  - "tox"
